version: '3.7'
services:

    server:
        build: .
        container_name: server
        environment:
            - PORT=8000
        expose:
          - 8080    
        ports:
            - 8080:8080
        volumes:
            - './:/usr/app'
        depends_on: 
            - redis
            - postgres

    redis:
      image: "redis:alpine" 
      restart: unless-stopped

    postgres:
      container_name: pg
      image: postgres
      environment:
        POSTGRES_DB: getmyprogram
        POSTGRES_USER: marcusmagnusson
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      restart: unless-stopped
