// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/francismarcus/eg/ent/shout"
	"github.com/francismarcus/eg/ent/user"
)

// ShoutCreate is the builder for creating a Shout entity.
type ShoutCreate struct {
	config
	mutation *ShoutMutation
	hooks    []Hook
}

// SetCreatedAt sets the created_at field.
func (sc *ShoutCreate) SetCreatedAt(t time.Time) *ShoutCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (sc *ShoutCreate) SetNillableCreatedAt(t *time.Time) *ShoutCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the updated_at field.
func (sc *ShoutCreate) SetUpdatedAt(t time.Time) *ShoutCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (sc *ShoutCreate) SetNillableUpdatedAt(t *time.Time) *ShoutCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetMessage sets the message field.
func (sc *ShoutCreate) SetMessage(s string) *ShoutCreate {
	sc.mutation.SetMessage(s)
	return sc
}

// SetLikes sets the likes field.
func (sc *ShoutCreate) SetLikes(i int) *ShoutCreate {
	sc.mutation.SetLikes(i)
	return sc
}

// SetNillableLikes sets the likes field if the given value is not nil.
func (sc *ShoutCreate) SetNillableLikes(i *int) *ShoutCreate {
	if i != nil {
		sc.SetLikes(*i)
	}
	return sc
}

// SetAuthorID sets the author edge to User by id.
func (sc *ShoutCreate) SetAuthorID(id int) *ShoutCreate {
	sc.mutation.SetAuthorID(id)
	return sc
}

// SetNillableAuthorID sets the author edge to User by id if the given value is not nil.
func (sc *ShoutCreate) SetNillableAuthorID(id *int) *ShoutCreate {
	if id != nil {
		sc = sc.SetAuthorID(*id)
	}
	return sc
}

// SetAuthor sets the author edge to User.
func (sc *ShoutCreate) SetAuthor(u *User) *ShoutCreate {
	return sc.SetAuthorID(u.ID)
}

// AddLikedByIDs adds the liked_by edge to User by ids.
func (sc *ShoutCreate) AddLikedByIDs(ids ...int) *ShoutCreate {
	sc.mutation.AddLikedByIDs(ids...)
	return sc
}

// AddLikedBy adds the liked_by edges to User.
func (sc *ShoutCreate) AddLikedBy(u ...*User) *ShoutCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return sc.AddLikedByIDs(ids...)
}

// Mutation returns the ShoutMutation object of the builder.
func (sc *ShoutCreate) Mutation() *ShoutMutation {
	return sc.mutation
}

// Save creates the Shout in the database.
func (sc *ShoutCreate) Save(ctx context.Context) (*Shout, error) {
	var (
		err  error
		node *Shout
	)
	sc.defaults()
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ShoutMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ShoutCreate) SaveX(ctx context.Context) *Shout {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (sc *ShoutCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := shout.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := shout.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.Likes(); !ok {
		v := shout.DefaultLikes
		sc.mutation.SetLikes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *ShoutCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New("ent: missing required field \"created_at\"")}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New("ent: missing required field \"updated_at\"")}
	}
	if _, ok := sc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New("ent: missing required field \"message\"")}
	}
	if _, ok := sc.mutation.Likes(); !ok {
		return &ValidationError{Name: "likes", err: errors.New("ent: missing required field \"likes\"")}
	}
	return nil
}

func (sc *ShoutCreate) sqlSave(ctx context.Context) (*Shout, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sc *ShoutCreate) createSpec() (*Shout, *sqlgraph.CreateSpec) {
	var (
		_node = &Shout{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: shout.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: shout.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shout.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: shout.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.Message(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: shout.FieldMessage,
		})
		_node.Message = value
	}
	if value, ok := sc.mutation.Likes(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: shout.FieldLikes,
		})
		_node.Likes = value
	}
	if nodes := sc.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shout.AuthorTable,
			Columns: []string{shout.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.LikedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   shout.LikedByTable,
			Columns: shout.LikedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShoutCreateBulk is the builder for creating a bulk of Shout entities.
type ShoutCreateBulk struct {
	config
	builders []*ShoutCreate
}

// Save creates the Shout entities in the database.
func (scb *ShoutCreateBulk) Save(ctx context.Context) ([]*Shout, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Shout, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShoutMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (scb *ShoutCreateBulk) SaveX(ctx context.Context) []*Shout {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
