// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/francismarcus/eg/ent/user"
	"github.com/francismarcus/eg/ent/usersettings"
)

// UserSettingsCreate is the builder for creating a UserSettings entity.
type UserSettingsCreate struct {
	config
	mutation *UserSettingsMutation
	hooks    []Hook
}

// SetGender sets the gender field.
func (usc *UserSettingsCreate) SetGender(u usersettings.Gender) *UserSettingsCreate {
	usc.mutation.SetGender(u)
	return usc
}

// SetNillableGender sets the gender field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableGender(u *usersettings.Gender) *UserSettingsCreate {
	if u != nil {
		usc.SetGender(*u)
	}
	return usc
}

// SetAge sets the age field.
func (usc *UserSettingsCreate) SetAge(i int) *UserSettingsCreate {
	usc.mutation.SetAge(i)
	return usc
}

// SetNillableAge sets the age field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableAge(i *int) *UserSettingsCreate {
	if i != nil {
		usc.SetAge(*i)
	}
	return usc
}

// SetWeight sets the weight field.
func (usc *UserSettingsCreate) SetWeight(i int) *UserSettingsCreate {
	usc.mutation.SetWeight(i)
	return usc
}

// SetNillableWeight sets the weight field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableWeight(i *int) *UserSettingsCreate {
	if i != nil {
		usc.SetWeight(*i)
	}
	return usc
}

// SetHeight sets the height field.
func (usc *UserSettingsCreate) SetHeight(i int) *UserSettingsCreate {
	usc.mutation.SetHeight(i)
	return usc
}

// SetNillableHeight sets the height field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableHeight(i *int) *UserSettingsCreate {
	if i != nil {
		usc.SetHeight(*i)
	}
	return usc
}

// SetLevel sets the level field.
func (usc *UserSettingsCreate) SetLevel(u usersettings.Level) *UserSettingsCreate {
	usc.mutation.SetLevel(u)
	return usc
}

// SetBelongsToID sets the belongs_to edge to User by id.
func (usc *UserSettingsCreate) SetBelongsToID(id int) *UserSettingsCreate {
	usc.mutation.SetBelongsToID(id)
	return usc
}

// SetBelongsTo sets the belongs_to edge to User.
func (usc *UserSettingsCreate) SetBelongsTo(u *User) *UserSettingsCreate {
	return usc.SetBelongsToID(u.ID)
}

// Mutation returns the UserSettingsMutation object of the builder.
func (usc *UserSettingsCreate) Mutation() *UserSettingsMutation {
	return usc.mutation
}

// Save creates the UserSettings in the database.
func (usc *UserSettingsCreate) Save(ctx context.Context) (*UserSettings, error) {
	var (
		err  error
		node *UserSettings
	)
	if len(usc.hooks) == 0 {
		if err = usc.check(); err != nil {
			return nil, err
		}
		node, err = usc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = usc.check(); err != nil {
				return nil, err
			}
			usc.mutation = mutation
			node, err = usc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(usc.hooks) - 1; i >= 0; i-- {
			mut = usc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (usc *UserSettingsCreate) SaveX(ctx context.Context) *UserSettings {
	v, err := usc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (usc *UserSettingsCreate) check() error {
	if v, ok := usc.mutation.Gender(); ok {
		if err := usersettings.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf("ent: validator failed for field \"gender\": %w", err)}
		}
	}
	if _, ok := usc.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New("ent: missing required field \"level\"")}
	}
	if v, ok := usc.mutation.Level(); ok {
		if err := usersettings.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf("ent: validator failed for field \"level\": %w", err)}
		}
	}
	if _, ok := usc.mutation.BelongsToID(); !ok {
		return &ValidationError{Name: "belongs_to", err: errors.New("ent: missing required edge \"belongs_to\"")}
	}
	return nil
}

func (usc *UserSettingsCreate) sqlSave(ctx context.Context) (*UserSettings, error) {
	_node, _spec := usc.createSpec()
	if err := sqlgraph.CreateNode(ctx, usc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (usc *UserSettingsCreate) createSpec() (*UserSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSettings{config: usc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: usersettings.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usersettings.FieldID,
			},
		}
	)
	if value, ok := usc.mutation.Gender(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: usersettings.FieldGender,
		})
		_node.Gender = &value
	}
	if value, ok := usc.mutation.Age(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: usersettings.FieldAge,
		})
		_node.Age = &value
	}
	if value, ok := usc.mutation.Weight(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: usersettings.FieldWeight,
		})
		_node.Weight = &value
	}
	if value, ok := usc.mutation.Height(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: usersettings.FieldHeight,
		})
		_node.Height = &value
	}
	if value, ok := usc.mutation.Level(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: usersettings.FieldLevel,
		})
		_node.Level = value
	}
	if nodes := usc.mutation.BelongsToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.BelongsToTable,
			Columns: []string{usersettings.BelongsToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserSettingsCreateBulk is the builder for creating a bulk of UserSettings entities.
type UserSettingsCreateBulk struct {
	config
	builders []*UserSettingsCreate
}

// Save creates the UserSettings entities in the database.
func (uscb *UserSettingsCreateBulk) Save(ctx context.Context) ([]*UserSettings, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uscb.builders))
	nodes := make([]*UserSettings, len(uscb.builders))
	mutators := make([]Mutator, len(uscb.builders))
	for i := range uscb.builders {
		func(i int, root context.Context) {
			builder := uscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uscb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uscb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (uscb *UserSettingsCreateBulk) SaveX(ctx context.Context) []*UserSettings {
	v, err := uscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
