// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Diet is the predicate function for diet builders.
type Diet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSettings is the predicate function for usersettings builders.
type UserSettings func(*sql.Selector)
